<?php

/**
 * This is the model base class for the table "items_hashes".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemsHashes".
 *
 * Columns in table "items_hashes" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $doc_id
 * @property integer $word_hash
 *
 */
abstract class BaseItemsHashes extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'items_hashes';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'ItemsHashes|ItemsHashes', $n);
    }

    public static function representingColumn()
    {
        return 'id';
    }

    public function rules()
    {
        return array(
            array('doc_id, word_hash', 'required'),
            array('doc_id, word_hash', 'numerical', 'integerOnly' => true),
            array('id, doc_id, word_hash', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id'        => Yii::t('app', 'ID'),
            'doc_id'    => Yii::t('app', 'Doc'),
            'word_hash' => Yii::t('app', 'Word Hash'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('doc_id', $this->doc_id);
        $criteria->compare('word_hash', $this->word_hash);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}