<?php

/**
 * This is the model base class for the table "news".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "News".
 *
 * Columns in table "news" available as properties of the model,
 * followed by relations of table "news" available as properties of the model.
 *
 * @property integer $id
 * @property integer $pending_news_id
 * @property string $title
 * @property string $content
 * @property string $thumb
 * @property string $status
 * @property string $created_at
 * @property string $updated_at
 *
 * @property PendingNews $pendingNews
 */
abstract class BaseNews extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'news';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'News|News', $n);
    }

    public static function representingColumn()
    {
        return 'title';
    }

    public function rules()
    {
        return array(
            array('pending_news_id', 'required'),
            array('pending_news_id', 'numerical', 'integerOnly' => true),
            array('status', 'length', 'max' => 10),
            array('title, content, thumb, created_at, updated_at', 'safe'),
            array(
                'title, content, thumb, status, created_at, updated_at',
                'default',
                'setOnEmpty' => true,
                'value'      => null
            ),
            array(
                'id, pending_news_id, title, content, thumb, status, created_at, updated_at',
                'safe',
                'on' => 'search'
            ),
        );
    }

    public function relations()
    {
        return array(
            'pendingNews' => array(self::BELONGS_TO, 'PendingNews', 'pending_news_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'pending_news_id' => null,
            'title' => Yii::t('app', 'Title'),
            'content' => Yii::t('app', 'Content'),
            'thumb' => Yii::t('app', 'Thumb'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'pendingNews' => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('pending_news_id', $this->pending_news_id);
        $criteria->compare('title', $this->title, true);
        $criteria->compare('content', $this->content, true);
        $criteria->compare('thumb', $this->thumb, true);
        $criteria->compare('status', $this->status, true);
        $criteria->compare('created_at', $this->created_at, true);
        $criteria->compare('updated_at', $this->updated_at, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}