<?php

/**
 * This is the model base class for the table "exclude_elements".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ExcludeElements".
 *
 * Columns in table "exclude_elements" available as properties of the model,
 * followed by relations of table "exclude_elements" available as properties of the model.
 *
 * @property integer $id
 * @property integer $source_id
 * @property string $pattern
 *
 * @property Sources $source
 */
abstract class BaseExcludeElements extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'exclude_elements';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'ExcludeElements|ExcludeElements', $n);
    }

    public static function representingColumn()
    {
        return 'pattern';
    }

    public function rules()
    {
        return array(
            array('source_id, pattern', 'required'),
            array('id, source_id', 'numerical', 'integerOnly' => true),
            array('id, source_id, pattern', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'source' => array(self::BELONGS_TO, 'Sources', 'source_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id'        => Yii::t('app', 'ID'),
            'source_id' => null,
            'pattern'   => Yii::t('app', 'Pattern'),
            'source'    => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('source_id', $this->source_id);
        $criteria->compare('pattern', $this->pattern, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}