<?php

/**
 * This is the model base class for the table "sources_settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SourcesSettings".
 *
 * Columns in table "sources_settings" available as properties of the model,
 * followed by relations of table "sources_settings" available as properties of the model.
 *
 * @property integer $id
 * @property integer $source_id
 * @property string $name
 * @property string $value
 *
 * @property Sources $source
 */
abstract class BaseSourcesSettings extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'sources_settings';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'SourcesSettings|SourcesSettings', $n);
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('source_id, name', 'required'),
            array('source_id', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('value', 'safe'),
            array('value', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, source_id, name, value', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'source' => array(self::BELONGS_TO, 'Sources', 'source_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id'        => Yii::t('app', 'ID'),
            'source_id' => null,
            'name'      => Yii::t('app', 'Name'),
            'value'     => Yii::t('app', 'Value'),
            'source'    => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('source_id', $this->source_id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('value', $this->value, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}