<?php

/**
 * This is the model base class for the table "lock_parser_queue".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LockParserQueue".
 *
 * Columns in table "lock_parser_queue" available as properties of the model,
 * followed by relations of table "lock_parser_queue" available as properties of the model.
 *
 * @property integer $id_parser_queue
 * @property string $created_at
 *
 * @property ParserQueue $idParserQueue
 */
abstract class BaseLockParserQueue extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'lock_parser_queue';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'LockParserQueue|LockParserQueues', $n);
    }

    public static function representingColumn()
    {
        return 'created_at';
    }

    public function rules()
    {
        return array(
            array('id_parser_queue', 'required'),
            array('id_parser_queue', 'numerical', 'integerOnly' => true),
            array('created_at', 'length', 'max' => 45),
            array('created_at', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id_parser_queue, created_at', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'idParserQueue' => array(self::BELONGS_TO, 'ParserQueue', 'id_parser_queue'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id_parser_queue' => null,
            'created_at'      => Yii::t('app', 'Created At'),
            'idParserQueue'   => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id_parser_queue', $this->id_parser_queue);
        $criteria->compare('created_at', $this->created_at, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}