<?php

/**
 * This is the model base class for the table "news_links".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsLinks".
 *
 * Columns in table "news_links" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_news
 * @property integer $id_pq
 *
 */
abstract class BaseNewsLinks extends GxActiveRecord
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'news_links';
    }

    public static function label($n = 1)
    {
        return Yii::t('app', 'NewsLinks|NewsLinks', $n);
    }

    public static function representingColumn()
    {
        return array(
            'id_news',
            'id_pq',
        );
    }

    public function rules()
    {
        return array(
            array('id_news, id_pq', 'required'),
            array('id_news, id_pq', 'numerical', 'integerOnly' => true),
            array('id_news, id_pq', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id_news' => null,
            'id_pq'   => null,
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id_news', $this->id_news);
        $criteria->compare('id_pq', $this->id_pq);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}